// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT1S0cB789830qHlUCKxJ8MKecLRH78vI',
    appId: '1:978020610103:web:ead1972c9be124fcc64fb2',
    messagingSenderId: '978020610103',
    projectId: 'crop-konnect',
    authDomain: 'crop-konnect.firebaseapp.com',
    storageBucket: 'crop-konnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdD_ab_dTF3jTfHrA9LqxQYqQ6GHMJOM',
    appId: '1:978020610103:android:32dc315869bff730c64fb2',
    messagingSenderId: '978020610103',
    projectId: 'crop-konnect',
    storageBucket: 'crop-konnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWUPbWJE_vpyVfEzjvrlh01Ym2gsCjhr4',
    appId: '1:978020610103:ios:bc54a12ac9dc99f1c64fb2',
    messagingSenderId: '978020610103',
    projectId: 'crop-konnect',
    storageBucket: 'crop-konnect.firebasestorage.app',
    iosBundleId: 'com.example.essSensorCk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWUPbWJE_vpyVfEzjvrlh01Ym2gsCjhr4',
    appId: '1:978020610103:ios:bc54a12ac9dc99f1c64fb2',
    messagingSenderId: '978020610103',
    projectId: 'crop-konnect',
    storageBucket: 'crop-konnect.firebasestorage.app',
    iosBundleId: 'com.example.essSensorCk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT1S0cB789830qHlUCKxJ8MKecLRH78vI',
    appId: '1:978020610103:web:7eafaab2dbb0cefac64fb2',
    messagingSenderId: '978020610103',
    projectId: 'crop-konnect',
    authDomain: 'crop-konnect.firebaseapp.com',
    storageBucket: 'crop-konnect.firebasestorage.app',
  );
}
